#nome da pipeline

name: Run Basic Tests

# em que momento será executada

on: 
   pull_request: 
    branches: [master]

jobs:
    # o que vai ser feito nessa pipeline
    # só teremos um job: rodar os testes
    cypress-run:
        # maquina que será executad0
        runs-on: ubuntu-latest

        #passo a passo para rodar os testes
        steps:
          - name: checkout/Clone do projeto
            uses: actions/checkout@v4
        
          #execução e configuração do projeto  
          - name: Run tests
            uses: cypress-io/github-action@v5
            with:
                record: true
            env: 
              CYPRESS_RECORD_KEY: ${ secrets.CYPRESS_RECORD_KEY }} 





